"""Third Migraton

Revision ID: 6c15ace5c153
Revises: c27f3518ec7e
Create Date: 2020-05-12 01:52:20.268972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c15ace5c153'
down_revision = 'c27f3518ec7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('message', sa.String(length=255), nullable=True))
    op.add_column('blogs', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('blogs', 'dislikes')
    op.drop_column('blogs', 'likes')
    op.drop_column('blogs', 'blog_title')
    op.drop_column('blogs', 'blog_content')
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'date_joined')
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('date_joined', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'password_hash')
    op.add_column('blogs', sa.Column('blog_content', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('blog_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'title')
    op.drop_column('blogs', 'message')
    # ### end Alembic commands ###
